---
# TODO: add force option
- name: 'Download SumoCollector tarball'
  get_url: url="{{ sumologic_installer_tarball_url }}" dest="{{ sumologic_installer_tarball_dest }}/sumocollector.tgz" mode=440
  when: sumologic_installer_tarball_url is defined
  tags:
      - sumologic

- name: 'Unarchive SumoCollector tarball'
  unarchive: src="{{ sumologic_installer_tarball_dest }}/sumocollector.tgz" dest="{{ sumologic_installer_tarball_dest }}" copy=no
  when: sumologic_installer_tarball_url is defined
  tags:
      - sumologic

# See: https://service.us2.sumologic.com/help/Default.htm#Tarball_installation_for_Linux.htm%3FTocPath%3DSending%2520Data%7CCollectors%7C%2520Installed%2520Collectors%2520%7CLinux%7C_____1
- name: "Symlink SumoCollector for instance architecture (32 or 64 bit)"
  file: src="{{ sumologic_installer_tarball_dest }}/sumocollector/tanuki/linux{{ ansible_userspace_bits }}/wrapper" dest="{{ sumologic_installer_tarball_dest }}/sumocollector/wrapper" state=link
  when: sumologic_installer_tarball_url is defined
  tags:
      - sumologic

- name: 'Check for SumoCollector'
  command: dpkg-query -l sumocollector
  register: sumologic_collector_deb_check
  failed_when: no
  tags: sumologic

- name: 'Download SumoCollector'
  get_url:
    url: '{{ sumocollector_installer_download }}'
    dest: '{{ sumologic_installer_remote_file }}'
  when: sumologic_collector_deb_check.rc == 1
  tags: sumologic

- name: 'Install SumoCollector'
  apt:
    deb: '{{ sumologic_installer_remote_file }}'
    state: installed
  when: sumologic_collector_deb_check.rc == 1
  tags: sumologic
  notify: Restart SumoCollector


- name: 'Download SumoCollector redhat'
  get_url:
    url: '{{ sumocollector_installer_rpm }}'
    dest: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
  when: ansible_os_family == "RedHat"
  tags: sumologic

- name: 'Install SumoCollector redhat'
  yum:
    name: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
    state: present
  when: ansible_os_family == "RedHat"
  tags: sumologic
  notify: Restart SumoCollector

- name: 'Configure SumoCollector'
  template:
    src: sumo.conf.j2
    dest: /etc/sumo.conf
  register: sumologic_collector_add_configuration
  tags: sumologic
  notify: Restart SumoCollector

- name: 'Define initial SumoCollector sources'
  set_fact:
    sumologic_collector_log_paths: "{{ sumologic_collector_default_log_path|list + sumologic_collector_application_log_path|list }}"
  tags: [sumologic, sumologic-collector]

- name: 'Create collector configuration'
  template:
    src: collector.json.j2
    dest: /etc/sumologic-collector.json
  tags: [sumologic, sumologic-collector]
  notify: Restart SumoCollector
